version: '3.9'
###
networks:
  hass:
  dockermacvlan:
    external: true
###
services:
  homeassistant:
    container_name: Home-Assistant
    image: homeassistant/home-assistant:stable
    user: 1001:1001
    networks:
      dockermacvlan:
        ipv4_address: 192.168.0.###
      hass:
    volumes:
      - ./config:/config
      - /docker/certbot/certs/live/<DOMAIN>/fullchain.pem:/ssl/fullchain.pem:ro
      - /docker/certbot/certs/live/<DOMAIN>/privkey.pem:/ssl/privkey.pem:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Australia/Melbourne
    restart: always
##
  whisper:
    container_name: Whisper
    image: rhasspy/wyoming-whisper
    user: 1001:1001
    networks:
      - hass
    volumes:
      - ./whisper:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: --model small --language en
    restart: always
##
  piper:
    container_name: Piper
    image: rhasspy/wyoming-piper
    user: 1001:1001
    networks:
      - hass
    volumes:
      - ./piper:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: --voice en-us-ryan-medium
    restart: always
##
